### ISSUE TITLE
what if use Hard Private modifiers

### ISSUE THREAD

**Issue by mikoloism** [fullstacksjs/config#4]
Just, replacing `private` modifier with hash character prefix to private a class member at compile-time and runtime

Typescript syntax:

``` typescript
class User {
    private name: string;
}
```
ECMAScript syntax:

``` javascript
class User {
    #name: string;
}
```

**WHY?**
[Because](https://levelup.gitconnected.com/ecmascript-vs-typescript-private-fields-640ae37aa162)

[Example of TS Private modifiers in `src/`](https://github.com/fullstacksjs/config/blob/main/src/Schema.ts#L9)

**Comment by ASafaeirad** [comment]
It's not a big deal but not a bad idea :+1: 
Feel free to open an PR

**Comment by ASafaeirad** [comment]
Now we need them to be protected, so we can close this issue.

**Comment by ASafaeirad** [comment]
Now we need them to be protected, so we can close this issue.
